# Generated by Django 5.0.6 on 2024-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("published_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("ano", models.IntegerField()),
                ("mail_id", models.EmailField(max_length=50)),
                ("phone_number", models.IntegerField()),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posting_date", models.DateField()),
                ("location", models.CharField(max_length=30)),
                ("offered_salary", models.FloatField()),
                ("qualification", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="eaddr",
            field=models.CharField(max_length=255),
        ),
    ]
